### Search Anime with Filters
POST http://localhost:3000/api/search
Content-Type: application/json

{
    "filters": [
        {
            "field": "year",
            "value": 2025,
            "action": "GREATER_THAN_OR_EQUALS",
            "score_multiplier": 1
        },
        {
            "field": "score",
            "value": 6.5,
            "action": "GREATER_THAN_OR_EQUALS",
            "score_multiplier": 1
        },
        {
            "field": "members",
            "value": 10000,
            "action": "GREATER_THAN_OR_EQUALS",
            "score_multiplier": 1
        },
        {
            "field": "type",
            "value": ["Movie"],
            "action": "INCLUDES_ANY",
            "score_multiplier": 1
        }
    ],
    "hideWatched": ["Completed", "Avoiding", "BRR"],
    "pagesize": 50,
    "airing": "no"
}

### Add Anime to Watched List
POST http://localhost:3000/watched/add
Content-Type: application/json

{
    "mal_ids": ["38903"],
    "status": "BRR"
}

### Get Anime Statistics
GET http://localhost:3000/api/stats/

### Get Available Anime Fields
GET http://localhost:3000/api/fields

### Get Available Filter Actions
GET http://localhost:3000/api/filters

### Get Watchlist by Status
GET http://localhost:3000/api/watchlist?status=Completed