### Search Manga with Filters
POST http://localhost:3000/api/manga/search
Content-Type: application/json

{
    "filters": [
        {
            "field": "genres",
            "value": ["Boys Love"],
            "action": "EXCLUDES"
        },
        {
            "field": "genres",
            "value": ["Comedy", "Action"],
            "action": "INCLUDES_ANY"
        },
        {
            "field": "genres",
            "value": ["Fantasy", "Mystery", "Supernatural"],
            "action": "INCLUDES_ANY"
        },
        {
            "field": "type",
            "value": "Manhwa",
            "action": "EQUALS"
        },
        {
            "field": "status",
            "value": "Finished",
            "action": "EQUALS"
        },
        {
            "field": "themes",
            "value": ["Villainess"],
            "action": "EXCLUDES"
        }
    ],
    "hideWatched": ["Completed", "Watching", "BRR"],
    "pagesize": 50,
    "sortBy": "score"
}

### Get Manga Statistics
GET http://localhost:3000/api/manga/stats

### Get Manga Watchlist
GET http://localhost:3000/api/manga/watchlist

### Add Manga to Watchlist - Completed
POST http://localhost:3000/api/manga/watched/add
Content-Type: application/json

{
    "mal_ids": ["29983"],
    "status": "Completed"
}
