name = "anime-list-web"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://mal-api.sarthakagrawal927.workers.dev"
NEXT_PUBLIC_SAASMAKER_API_KEY = "pk_fb1fe870205272a447298bfac32122383426d6a1c1fb10ab"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "207924374505-0mur9a99sal0ckob0vt38pcdj360ond5.apps.googleusercontent.com"
